// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReyesAR.BasedeDatos;

#nullable disable

namespace ReyesAR.Migrations
{
    [DbContext(typeof(ReyesARContext))]
    [Migration("20260331194143_Entregas")]
    partial class Entregas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmpresaEntity", b =>
                {
                    b.Property<string>("claveProveedor")
                        .HasColumnType("varchar(18)");

                    b.Property<string>("razonSocial")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("rfc")
                        .IsRequired()
                        .HasColumnType("varchar(13)");

                    b.HasKey("claveProveedor");

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("EntregaEntity", b =>
                {
                    b.Property<string>("claveEntrega")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(18)")
                        .HasColumnName("claveEntrega")
                        .HasDefaultValueSql("generar_clave_entrega()");

                    b.Property<string>("RepresentanteEntityclaveRepresentante")
                        .HasColumnType("varchar(18)");

                    b.Property<string>("clavePedido")
                        .IsRequired()
                        .HasColumnType("varchar(18)");

                    b.Property<string>("claveProveedor")
                        .IsRequired()
                        .HasColumnType("varchar(18)");

                    b.Property<string>("claveRepresentante")
                        .HasColumnType("varchar(18)");

                    b.Property<string>("claveUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(18)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("fecha_entrega")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_entrega")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("tipo_entrega")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo_entrega");

                    b.Property<decimal>("total")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total");

                    b.HasKey("claveEntrega");

                    b.HasIndex("RepresentanteEntityclaveRepresentante");

                    b.HasIndex("clavePedido")
                        .IsUnique();

                    b.HasIndex("claveProveedor");

                    b.HasIndex("claveRepresentante");

                    b.HasIndex("claveUsuario");

                    b.ToTable("Entregas", (string)null);
                });

            modelBuilder.Entity("IndependienteEntity", b =>
                {
                    b.Property<string>("claveProveedor")
                        .HasColumnType("varchar(18)");

                    b.Property<string>("apellidoMaterno")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("apellidoPaterno")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("tipoServicio")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("claveProveedor");

                    b.ToTable("Independientes", (string)null);
                });

            modelBuilder.Entity("ReyesAR.Models.CategoriaEntity", b =>
                {
                    b.Property<string>("claveCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(18)")
                        .HasDefaultValueSql("generar_clave_Categoria()");

                    b.Property<string>("claveDepartamento")
                        .IsRequired()
                        .HasColumnType("varchar(18)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("estado")
                        .HasColumnType("boolean")
                        .HasColumnName("estado");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("claveCategoria")
                        .HasName("PK_ClaveCategoria");

                    b.HasIndex("claveDepartamento");

                    b.ToTable("Categorias", (string)null);
                });

            modelBuilder.Entity("ReyesAR.Models.DepartamentoEntity", b =>
                {
                    b.Property<string>("claveDepartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(18)")
                        .HasDefaultValueSql("generar_clave_departamento()");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("fecha_creacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("claveDepartamento")
                        .HasName("PK_ClaveDepartamento");

                    b.ToTable("Departamentos", (string)null);
                });

            modelBuilder.Entity("ReyesAR.Models.DetallePedidoEntity", b =>
                {
                    b.Property<string>("Clavepedido")
                        .HasColumnType("varchar(18)")
                        .HasColumnName("Clavepedido");

                    b.Property<string>("Claveproducto")
                        .HasColumnType("varchar(18)")
                        .HasColumnName("Claveproducto");

                    b.Property<decimal>("cantidad")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cantidad");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("tipo_detalle")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo_detalle");

                    b.HasKey("Clavepedido", "Claveproducto");

                    b.HasIndex("Claveproducto");

                    b.ToTable("DetallePedido", (string)null);
                });

            modelBuilder.Entity("ReyesAR.Models.EmpleadoEntity", b =>
                {
                    b.Property<string>("claveEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(18)")
                        .HasColumnName("claveEmpleado")
                        .HasDefaultValueSql("generar_clave_empleado()");

                    b.Property<string>("apellido_materno")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apellido_materno");

                    b.Property<string>("apellido_paterno")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apellido_paterno");

                    b.Property<string>("curp")
                        .IsRequired()
                        .HasColumnType("varchar(18)")
                        .HasColumnName("curp");

                    b.Property<bool>("estado")
                        .HasColumnType("boolean")
                        .HasColumnName("estado");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnName("telefono");

                    b.HasKey("claveEmpleado");

                    b.HasIndex("curp")
                        .IsUnique();

                    b.ToTable("Empleados", (string)null);
                });

            modelBuilder.Entity("ReyesAR.Models.EmpleadoRolEntity", b =>
                {
                    b.Property<string>("claveEmpleado")
                        .HasColumnType("varchar(18)")
                        .HasColumnName("claveEmpleado");

                    b.Property<string>("claveRol")
                        .HasColumnType("varchar(18)")
                        .HasColumnName("claveRol");

                    b.Property<DateTime>("fecha_inicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<DateTime?>("fecha_fin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.HasKey("claveEmpleado", "claveRol", "fecha_inicio");

                    b.HasIndex("claveRol");

                    b.ToTable("EmpleadoRol", (string)null);
                });

            modelBuilder.Entity("ReyesAR.Models.EquivalenciaUnidadEntity", b =>
                {
                    b.Property<string>("claveProducto")
                        .HasColumnType("varchar(18)")
                        .HasColumnName("claveProducto");

                    b.Property<string>("claveUnidadCompra")
                        .HasColumnType("varchar(18)")
                        .HasColumnName("claveUnidadCompra");

                    b.Property<decimal>("factor_conversion")
                        .HasColumnType("numeric")
                        .HasColumnName("factor_conversion");

                    b.Property<string>("unidad_base")
                        .IsRequired()
                        .HasColumnType("nombre_unidad_enum")
                        .HasColumnName("unidad_base");

                    b.HasKey("claveProducto", "claveUnidadCompra");

                    b.HasIndex("claveUnidadCompra");

                    b.ToTable("EquivalenciasUnidad", (string)null);
                });

            modelBuilder.Entity("ReyesAR.Models.EquivalenciaUnidadVentaEntity", b =>
                {
                    b.Property<string>("claveProducto")
                        .HasColumnType("varchar(18)")
                        .HasColumnName("claveProducto");

                    b.Property<string>("claveUnidadVenta")
                        .HasColumnType("varchar(18)")
                        .HasColumnName("claveUnidadVenta");

                    b.Property<decimal>("factor_conversion")
                        .HasColumnType("numeric")
                        .HasColumnName("factor_conversion");

                    b.Property<string>("unidad_base")
                        .IsRequired()
                        .HasColumnType("nombre_unidad_enum")
                        .HasColumnName("unidad_base");

                    b.HasKey("claveProducto", "claveUnidadVenta");

                    b.HasIndex("claveUnidadVenta");

                    b.ToTable("EquivalenciasUnidadVentas", (string)null);
                });

            modelBuilder.Entity("ReyesAR.Models.PedidoEntity", b =>
                {
                    b.Property<string>("clavePedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(18)")
                        .HasColumnName("clavepedido")
                        .HasDefaultValueSql("generar_clave_pedido()");

                    b.Property<string>("claveProveedor")
                        .IsRequired()
                        .HasColumnType("varchar(18)")
                        .HasColumnName("claveproveedor");

                    b.Property<string>("claveUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(18)")
                        .HasColumnName("claveusuario");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("fecha_pedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_pedido")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("observaciones")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("observaciones");

                    b.Property<string>("tipo_pedido")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo_pedido");

                    b.Property<decimal>("total")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("total");

                    b.HasKey("clavePedido");

                    b.HasIndex("claveProveedor");

                    b.HasIndex("claveUsuario");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("ReyesAR.Models.ProductoEntity", b =>
                {
                    b.Property<string>("claveProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(18)")
                        .HasDefaultValueSql("generar_clave_producto()");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<bool>("caducidad")
                        .HasColumnType("boolean");

                    b.Property<decimal>("cantidad")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("claveCategoria")
                        .IsRequired()
                        .HasColumnType("varchar(18)");

                    b.Property<string>("claveProveedor")
                        .IsRequired()
                        .HasColumnType("varchar(18)");

                    b.Property<string>("claveUnidadMedida")
                        .IsRequired()
                        .HasColumnType("varchar(18)");

                    b.Property<string>("claveUnidadVenta")
                        .IsRequired()
                        .HasColumnType("varchar(18)");

                    b.Property<string>("codigo_barras")
                        .IsRequired()
                        .HasColumnType("varchar(13)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal>("margen_ganancia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(1.30m);

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("precio")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("precio_venta")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("tipo_producto")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("claveProducto")
                        .HasName("PK_ClaveProducto");

                    b.HasIndex("claveCategoria");

                    b.HasIndex("claveProveedor");

                    b.HasIndex("claveUnidadMedida");

                    b.HasIndex("claveUnidadVenta");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("ReyesAR.Models.ProveedorEntity", b =>
                {
                    b.Property<string>("claveProveedor")
                        .HasColumnType("varchar(18)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("estado")
                        .HasColumnType("boolean");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("tipo_proveedor")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("claveProveedor")
                        .HasName("PK_ClaveProveedor");

                    b.ToTable("Proveedores", (string)null);
                });

            modelBuilder.Entity("ReyesAR.Models.RepresentanteEntity", b =>
                {
                    b.Property<string>("claveRepresentante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(18)")
                        .HasColumnName("claveRepresentante")
                        .HasDefaultValueSql("generar_clave_representante()");

                    b.Property<string>("apellido_materno")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apellido_materno");

                    b.Property<string>("apellido_paterno")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apellido_paterno");

                    b.Property<string>("claveProveedor")
                        .IsRequired()
                        .HasColumnType("varchar(18)")
                        .HasColumnName("claveproveedor");

                    b.Property<bool>("estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnName("telefono");

                    b.Property<string>("tipo_representante")
                        .IsRequired()
                        .HasColumnType("tipo_representante_enum")
                        .HasColumnName("tipo_representante");

                    b.HasKey("claveRepresentante");

                    b.HasIndex("claveProveedor");

                    b.ToTable("Representantes", (string)null);
                });

            modelBuilder.Entity("ReyesAR.Models.RolEntity", b =>
                {
                    b.Property<string>("ClaveRol")
                        .HasColumnType("varchar(18)")
                        .HasColumnName("claveRol");

                    b.Property<bool>("activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("fecha_creacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("ClaveRol");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("ReyesAR.Models.UnidadCompraEntity", b =>
                {
                    b.Property<string>("claveUnidadCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(18)")
                        .HasDefaultValueSql("generar_clave_unidadCompra()");

                    b.Property<string>("abreviatura")
                        .IsRequired()
                        .HasColumnType("abreviatura_unidad_nuevo");

                    b.Property<bool>("estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("nombre_unidad")
                        .IsRequired()
                        .HasColumnType("tipo_unidad_nuevo");

                    b.Property<string>("tipo_stock")
                        .IsRequired()
                        .HasColumnType("tipo_valor_enum");

                    b.HasKey("claveUnidadCompra")
                        .HasName("PK_ClaveunidadCompra");

                    b.ToTable("UnidadCompras", (string)null);
                });

            modelBuilder.Entity("ReyesAR.Models.UnidadMedidaEntity", b =>
                {
                    b.Property<string>("claveUnidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(18)")
                        .HasDefaultValueSql("generar_clave_unidad()");

                    b.Property<string>("abreviatura")
                        .IsRequired()
                        .HasColumnType("abreviatura_unidad_enum");

                    b.Property<bool>("estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("nombreUnidad")
                        .IsRequired()
                        .HasColumnType("nombre_unidad_enum");

                    b.Property<string>("tipoStock")
                        .IsRequired()
                        .HasColumnType("tipo_stock_enum");

                    b.HasKey("claveUnidad")
                        .HasName("PK_ClaveUnidad");

                    b.ToTable("UnidadMedidas", (string)null);
                });

            modelBuilder.Entity("ReyesAR.Models.UnidadVentaEntity", b =>
                {
                    b.Property<string>("claveUnidadVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(18)")
                        .HasDefaultValueSql("generar_clave_unidadVenta()");

                    b.Property<string>("abreviatura")
                        .IsRequired()
                        .HasColumnType("abreviatura_unidad_venta_enum");

                    b.Property<bool>("estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("nombreUnidad")
                        .IsRequired()
                        .HasColumnType("nombre_unidad_venta_enum");

                    b.Property<string>("tipoValor")
                        .IsRequired()
                        .HasColumnType("tipo_valor_enum");

                    b.HasKey("claveUnidadVenta")
                        .HasName("PK_ClaveUnidadVenta");

                    b.ToTable("UnidadVentas", (string)null);
                });

            modelBuilder.Entity("ReyesAR.Models.UsuarioEntity", b =>
                {
                    b.Property<string>("claveUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(18)")
                        .HasColumnName("claveUsuario")
                        .HasDefaultValueSql("generar_clave_usuario()");

                    b.Property<string>("claveEmpleado")
                        .IsRequired()
                        .HasColumnType("varchar(18)")
                        .HasColumnName("claveEmpleado");

                    b.Property<string>("contrasena")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("contrasena");

                    b.Property<bool?>("estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<string>("nombre_usuario")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre_usuario");

                    b.HasKey("claveUsuario");

                    b.HasIndex("claveEmpleado")
                        .IsUnique();

                    b.HasIndex("nombre_usuario")
                        .IsUnique()
                        .HasDatabaseName("uq_nombre_usuario");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("EmpresaEntity", b =>
                {
                    b.HasOne("ReyesAR.Models.ProveedorEntity", "Proveedor")
                        .WithOne("Empresa")
                        .HasForeignKey("EmpresaEntity", "claveProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("EntregaEntity", b =>
                {
                    b.HasOne("ReyesAR.Models.RepresentanteEntity", null)
                        .WithMany("Entregas")
                        .HasForeignKey("RepresentanteEntityclaveRepresentante");

                    b.HasOne("ReyesAR.Models.PedidoEntity", "Pedido")
                        .WithOne("Entrega")
                        .HasForeignKey("EntregaEntity", "clavePedido")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReyesAR.Models.ProveedorEntity", "Proveedor")
                        .WithMany("Entregas")
                        .HasForeignKey("claveProveedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReyesAR.Models.RepresentanteEntity", "Representante")
                        .WithMany()
                        .HasForeignKey("claveRepresentante")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ReyesAR.Models.UsuarioEntity", "Usuario")
                        .WithMany("Entregas")
                        .HasForeignKey("claveUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Proveedor");

                    b.Navigation("Representante");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("IndependienteEntity", b =>
                {
                    b.HasOne("ReyesAR.Models.ProveedorEntity", "Proveedor")
                        .WithOne("Independiente")
                        .HasForeignKey("IndependienteEntity", "claveProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("ReyesAR.Models.CategoriaEntity", b =>
                {
                    b.HasOne("ReyesAR.Models.DepartamentoEntity", "Departamento")
                        .WithMany("Categorias")
                        .HasForeignKey("claveDepartamento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("ReyesAR.Models.DetallePedidoEntity", b =>
                {
                    b.HasOne("ReyesAR.Models.PedidoEntity", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("Clavepedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReyesAR.Models.ProductoEntity", "Producto")
                        .WithMany("Detalles")
                        .HasForeignKey("Claveproducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ReyesAR.Models.EmpleadoRolEntity", b =>
                {
                    b.HasOne("ReyesAR.Models.EmpleadoEntity", "Empleado")
                        .WithMany("RolesHistorial")
                        .HasForeignKey("claveEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReyesAR.Models.RolEntity", "Rol")
                        .WithMany("EmpleadosAsignados")
                        .HasForeignKey("claveRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ReyesAR.Models.EquivalenciaUnidadEntity", b =>
                {
                    b.HasOne("ReyesAR.Models.ProductoEntity", "Producto")
                        .WithMany("Equivalencias")
                        .HasForeignKey("claveProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReyesAR.Models.UnidadCompraEntity", "UnidadCompra")
                        .WithMany("EquivalenciasUnidad")
                        .HasForeignKey("claveUnidadCompra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("UnidadCompra");
                });

            modelBuilder.Entity("ReyesAR.Models.EquivalenciaUnidadVentaEntity", b =>
                {
                    b.HasOne("ReyesAR.Models.ProductoEntity", "Producto")
                        .WithMany("EquivalenciaProductoVenta")
                        .HasForeignKey("claveProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReyesAR.Models.UnidadVentaEntity", "UnidadVenta")
                        .WithMany("EquivalenciasUnidadVenta")
                        .HasForeignKey("claveUnidadVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("UnidadVenta");
                });

            modelBuilder.Entity("ReyesAR.Models.PedidoEntity", b =>
                {
                    b.HasOne("ReyesAR.Models.ProveedorEntity", "Proveedor")
                        .WithMany("Pedidos")
                        .HasForeignKey("claveProveedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReyesAR.Models.UsuarioEntity", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("claveUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ReyesAR.Models.ProductoEntity", b =>
                {
                    b.HasOne("ReyesAR.Models.CategoriaEntity", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("claveCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReyesAR.Models.ProveedorEntity", "Proveedor")
                        .WithMany("Productos")
                        .HasForeignKey("claveProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReyesAR.Models.UnidadMedidaEntity", "UnidadMedida")
                        .WithMany("Productos")
                        .HasForeignKey("claveUnidadMedida")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReyesAR.Models.UnidadVentaEntity", "UnidadVenta")
                        .WithMany("Productos")
                        .HasForeignKey("claveUnidadVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Proveedor");

                    b.Navigation("UnidadMedida");

                    b.Navigation("UnidadVenta");
                });

            modelBuilder.Entity("ReyesAR.Models.RepresentanteEntity", b =>
                {
                    b.HasOne("ReyesAR.Models.ProveedorEntity", "Proveedor")
                        .WithMany("Representantes")
                        .HasForeignKey("claveProveedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("ReyesAR.Models.UsuarioEntity", b =>
                {
                    b.HasOne("ReyesAR.Models.EmpleadoEntity", "Empleado")
                        .WithOne("Usuario")
                        .HasForeignKey("ReyesAR.Models.UsuarioEntity", "claveEmpleado")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("ReyesAR.Models.CategoriaEntity", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ReyesAR.Models.DepartamentoEntity", b =>
                {
                    b.Navigation("Categorias");
                });

            modelBuilder.Entity("ReyesAR.Models.EmpleadoEntity", b =>
                {
                    b.Navigation("RolesHistorial");

                    b.Navigation("Usuario")
                        .IsRequired();
                });

            modelBuilder.Entity("ReyesAR.Models.PedidoEntity", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Entrega");
                });

            modelBuilder.Entity("ReyesAR.Models.ProductoEntity", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("EquivalenciaProductoVenta");

                    b.Navigation("Equivalencias");
                });

            modelBuilder.Entity("ReyesAR.Models.ProveedorEntity", b =>
                {
                    b.Navigation("Empresa")
                        .IsRequired();

                    b.Navigation("Entregas");

                    b.Navigation("Independiente")
                        .IsRequired();

                    b.Navigation("Pedidos");

                    b.Navigation("Productos");

                    b.Navigation("Representantes");
                });

            modelBuilder.Entity("ReyesAR.Models.RepresentanteEntity", b =>
                {
                    b.Navigation("Entregas");
                });

            modelBuilder.Entity("ReyesAR.Models.RolEntity", b =>
                {
                    b.Navigation("EmpleadosAsignados");
                });

            modelBuilder.Entity("ReyesAR.Models.UnidadCompraEntity", b =>
                {
                    b.Navigation("EquivalenciasUnidad");
                });

            modelBuilder.Entity("ReyesAR.Models.UnidadMedidaEntity", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ReyesAR.Models.UnidadVentaEntity", b =>
                {
                    b.Navigation("EquivalenciasUnidadVenta");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ReyesAR.Models.UsuarioEntity", b =>
                {
                    b.Navigation("Entregas");

                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
