// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReyesAR.BasedeDatos;

#nullable disable

namespace ReyesAR.Migrations
{
    [DbContext(typeof(ReyesARContext))]
    [Migration("20260329214612_AddEstadoToCategorias")]
    partial class AddEstadoToCategorias
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmpresaEntity", b =>
                {
                    b.Property<string>("claveProveedor")
                        .HasColumnType("varchar(18)");

                    b.Property<string>("razonSocial")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("rfc")
                        .IsRequired()
                        .HasColumnType("varchar(13)");

                    b.HasKey("claveProveedor");

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("IndependienteEntity", b =>
                {
                    b.Property<string>("claveProveedor")
                        .HasColumnType("varchar(18)");

                    b.Property<string>("apellidoMaterno")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("apellidoPaterno")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("tipoServicio")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("claveProveedor");

                    b.ToTable("Independientes", (string)null);
                });

            modelBuilder.Entity("ReyesAR.Models.CategoriaEntity", b =>
                {
                    b.Property<string>("claveCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(18)")
                        .HasDefaultValueSql("generar_clave_Categoria()");

                    b.Property<string>("claveDepartamento")
                        .IsRequired()
                        .HasColumnType("varchar(18)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("estado")
                        .HasColumnType("boolean");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("claveCategoria")
                        .HasName("PK_ClaveCategoria");

                    b.HasIndex("claveDepartamento");

                    b.ToTable("Categorias", (string)null);
                });

            modelBuilder.Entity("ReyesAR.Models.DepartamentoEntity", b =>
                {
                    b.Property<string>("claveDepartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(18)")
                        .HasDefaultValueSql("generar_clave_departamento()");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("fecha_creacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("claveDepartamento")
                        .HasName("PK_ClaveDepartamento");

                    b.ToTable("Departamentos", (string)null);
                });

            modelBuilder.Entity("ReyesAR.Models.ProductoEntity", b =>
                {
                    b.Property<string>("claveProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(18)")
                        .HasDefaultValueSql("generar_clave_producto()");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<bool>("caducidad")
                        .HasColumnType("boolean");

                    b.Property<decimal>("cantidad")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("claveCategoria")
                        .IsRequired()
                        .HasColumnType("varchar(18)");

                    b.Property<string>("claveProveedor")
                        .IsRequired()
                        .HasColumnType("varchar(18)");

                    b.Property<string>("claveUnidadMedida")
                        .IsRequired()
                        .HasColumnType("varchar(18)");

                    b.Property<string>("claveUnidadVenta")
                        .IsRequired()
                        .HasColumnType("varchar(18)");

                    b.Property<string>("codigo_barras")
                        .IsRequired()
                        .HasColumnType("varchar(13)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal>("margen_ganancia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(1.30m);

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("precio")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("precio_venta")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("tipo_producto")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("claveProducto")
                        .HasName("PK_ClaveProducto");

                    b.HasIndex("claveCategoria");

                    b.HasIndex("claveProveedor");

                    b.HasIndex("claveUnidadMedida");

                    b.HasIndex("claveUnidadVenta");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("ReyesAR.Models.ProveedorEntity", b =>
                {
                    b.Property<string>("claveProveedor")
                        .HasColumnType("varchar(18)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("estado")
                        .HasColumnType("boolean");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("tipo_proveedor")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("claveProveedor")
                        .HasName("PK_ClaveProveedor");

                    b.ToTable("Proveedores", (string)null);
                });

            modelBuilder.Entity("ReyesAR.Models.UnidadCompraEntity", b =>
                {
                    b.Property<string>("claveUnidadCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(18)")
                        .HasDefaultValueSql("generar_clave_unidadCompra()");

                    b.Property<string>("abreviatura")
                        .IsRequired()
                        .HasColumnType("abreviatura_unidad_nuevo");

                    b.Property<bool>("estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("nombre_unidad")
                        .IsRequired()
                        .HasColumnType("tipo_unidad_nuevo");

                    b.Property<string>("tipo_stock")
                        .IsRequired()
                        .HasColumnType("tipo_valor_enum");

                    b.HasKey("claveUnidadCompra")
                        .HasName("PK_ClaveunidadCompra");

                    b.ToTable("UnidadCompras", (string)null);
                });

            modelBuilder.Entity("ReyesAR.Models.UnidadMedidaEntity", b =>
                {
                    b.Property<string>("claveUnidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(18)")
                        .HasDefaultValueSql("generar_clave_unidad()");

                    b.Property<string>("abreviatura")
                        .IsRequired()
                        .HasColumnType("abreviatura_unidad_enum");

                    b.Property<bool>("estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("nombreUnidad")
                        .IsRequired()
                        .HasColumnType("nombre_unidad_enum");

                    b.Property<string>("tipoStock")
                        .IsRequired()
                        .HasColumnType("tipo_stock_enum");

                    b.HasKey("claveUnidad")
                        .HasName("PK_ClaveUnidad");

                    b.ToTable("UnidadMedidas", (string)null);
                });

            modelBuilder.Entity("ReyesAR.Models.UnidadVentaEntity", b =>
                {
                    b.Property<string>("claveUnidadVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(18)")
                        .HasDefaultValueSql("generar_clave_unidadVenta()");

                    b.Property<string>("abreviatura")
                        .IsRequired()
                        .HasColumnType("abreviatura_unidad_venta_enum");

                    b.Property<bool>("estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("nombreUnidad")
                        .IsRequired()
                        .HasColumnType("nombre_unidad_venta_enum");

                    b.Property<string>("tipoValor")
                        .IsRequired()
                        .HasColumnType("tipo_valor_enum");

                    b.HasKey("claveUnidadVenta")
                        .HasName("PK_ClaveUnidadVenta");

                    b.ToTable("UnidadVentas", (string)null);
                });

            modelBuilder.Entity("EmpresaEntity", b =>
                {
                    b.HasOne("ReyesAR.Models.ProveedorEntity", "Proveedor")
                        .WithOne("Empresa")
                        .HasForeignKey("EmpresaEntity", "claveProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("IndependienteEntity", b =>
                {
                    b.HasOne("ReyesAR.Models.ProveedorEntity", "Proveedor")
                        .WithOne("Independiente")
                        .HasForeignKey("IndependienteEntity", "claveProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("ReyesAR.Models.CategoriaEntity", b =>
                {
                    b.HasOne("ReyesAR.Models.DepartamentoEntity", "Departamento")
                        .WithMany("Categorias")
                        .HasForeignKey("claveDepartamento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("ReyesAR.Models.ProductoEntity", b =>
                {
                    b.HasOne("ReyesAR.Models.CategoriaEntity", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("claveCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReyesAR.Models.ProveedorEntity", "Proveedor")
                        .WithMany("Productos")
                        .HasForeignKey("claveProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReyesAR.Models.UnidadMedidaEntity", "UnidadMedida")
                        .WithMany("Productos")
                        .HasForeignKey("claveUnidadMedida")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReyesAR.Models.UnidadVentaEntity", "UnidadVenta")
                        .WithMany("Productos")
                        .HasForeignKey("claveUnidadVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Proveedor");

                    b.Navigation("UnidadMedida");

                    b.Navigation("UnidadVenta");
                });

            modelBuilder.Entity("ReyesAR.Models.CategoriaEntity", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ReyesAR.Models.DepartamentoEntity", b =>
                {
                    b.Navigation("Categorias");
                });

            modelBuilder.Entity("ReyesAR.Models.ProveedorEntity", b =>
                {
                    b.Navigation("Empresa")
                        .IsRequired();

                    b.Navigation("Independiente")
                        .IsRequired();

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ReyesAR.Models.UnidadMedidaEntity", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ReyesAR.Models.UnidadVentaEntity", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
